is_dev: true
port: 8001
owner_id: 0
register_key: ""
domain_url: "https://example.com"
cache_dir: "static/asset"
bot_config:
  bot_token: ""
  hook_url: "https://example.com/api"
  is_webhook: false

meili_config:
  host: "http://127.0.0.1:7700"
  key: ""
