name: docker-deploy
on:
  push: 
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build dokcer image
        run: make build
      
      - name: list build directory contents
        run: ls -l .

      - name: Copy image to remote.
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_ACCOUNT }}
          key: ${{ secrets.LINODE_SECRET }}
          port: 10022
          source: "./gotein.tar"
          target: "~"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_ACCOUNT }}
          key: ${{ secrets.LINODE_SECRET }}
          port: 10022
          script: |
            docker load -i $HOME/gotein.tar
            systemctl restart ${{ secrets.SERVICE_NAME }}
